### ISSUE TITLE
Error on react-hot-loader and async

### ISSUE THREAD

**Issue by GravityMsc** [GravityMsc/gravitymsc.github.io#3]
gaearon/react-hot-loader#391
when using react-hot-loader,  
`
  const func = async () => {
    // If you use **this**, it will show in console
>  this is not undefined

}
`

**Comment by yakovenkoroman1993** [comment]
I have same problem too. I use react-hot-loader and babel-plugin-transform-async-to-generator
![image](https://user-images.githubusercontent.com/13461433/35134798-3a21b0fc-fd0b-11e7-8ad9-7c3188f4b2a6.png)

**Comment by GravityMsc** [comment]
@yakovenkoroman1993 Thanks for your help and I'll try it. And according that issue, this problem will be repaired in react-hot-loader v4
